### ISSUE TITLE
Support additional type "Utility"

### ISSUE THREAD

**Issue by flipactual** [emdaer/emdaer#54]
per https://github.com/emdaer/emdaer/pull/53#issuecomment-313889406

A Utility should have one of a defined set of return types (string, array, matrix, etc) and Plugins that support any given return type should have a specified common key in place where that type is accepted and use 

```yml
- plugin: my-plugin
  options:
    contentFromMatrixUtility:
      utility: returns-a-matrix
```
